name: Build epp

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [10.x]

    steps:      
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: echo -e "HiddenData = ${{secrets.HiddenData}}\nipList = ${{secrets.ipList}}\nipListMine = ${{secrets.ipListMine}}" >> .env
    - run: pm2 restart pxseu.com
