name: Build website NEXT.JS

on:
    push:
        branches: [senpai]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using ssh key
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  script: |
                      export NVM_DIR=~/.nvm
                      source ~/.nvm/nvm.sh
                      cd ~/deploy/pxseu.com
                      git reset --hard
                      git pull
                      yarn
                      cp ../.env .env
                      yarn deploy
                      pm2 restart pxseu.com
